# -*- coding: utf-8 -*-
"""GNN-Based BERT for Understanding Context from  Music.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DBkLyCM8jP7actQS2hI8eyWkCzkYgMz
"""

!nvidia-smi

import sys
import torch

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

!pip install -q librosa transformers datasets scikit-learn pandas numpy matplotlib seaborn tqdm pyyaml

!pip install -q torch-geometric

import torch_geometric

print("PyTorch Geometric:", torch_geometric.__version__)

import os
import json
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import librosa
import librosa.display

from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    average_precision_score
)

from transformers import (
    AutoTokenizer,
    AutoModel
)

from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GraphSAGE, GATConv, global_mean_pool

print("All imports successful!")

PROJECT_DIR = "/content/gnn-bert-music-context"

folders = [
    "data/raw",
    "data/processed",
    "data/graphs",
    "data/features",
    "data/splits",
    "notebooks",
    "src",
    "results/plots",
    "results/retrieval_examples",
    "report"
]

for folder in folders:
    os.makedirs(os.path.join(PROJECT_DIR, folder), exist_ok=True)

print("Project directory:", PROJECT_DIR)

for root, dirs, files in os.walk(PROJECT_DIR):
    level = root.replace(PROJECT_DIR, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("Seed set to:", SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

if device.type == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "GPU memory:",
        round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
        "GB"
    )

# Commented out IPython magic to ensure Python compatibility.
import os

DATA_DIR = "/content/gnn-bert-music-context/data/raw"
os.makedirs(DATA_DIR, exist_ok=True)

# %cd $DATA_DIR

!wget -q --show-progress https://os.unil.ch/metadata/fma_metadata.zip #wwrong command

!ls -lh

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gnn-bert-music-context/data/raw

!wget -q --show-progress https://os.unil.cloud.switch.ch/fma/fma_metadata.zip #fixed it
!wget -q --show-progress https://os.unil.cloud.switch.ch/fma/fma_small.zip

!ls -lh

!echo "f0df49ffe5f2a6008d7dc83c6915b31835dfe733  fma_metadata.zip" | sha1sum -c -
!echo "ade154f733639d52e35e32f5593efe5be76c6d70  fma_small.zip" | sha1sum -c -

!unzip -q fma_metadata.zip
!unzip -q fma_small.zip
!ls -lh

import pandas as pd

METADATA_DIR = "/content/gnn-bert-music-context/data/raw/fma_metadata"

tracks = pd.read_csv(f"{METADATA_DIR}/tracks.csv", index_col=0, header=[0, 1])
genres = pd.read_csv(f"{METADATA_DIR}/genres.csv", index_col=0)

# filter to the small subset
small = tracks[tracks[('set', 'subset')] == 'small']
print(small.shape)
small[('track', 'genre_top')].value_counts()

#task1 buildup
text_cols = [c for c in tracks.columns if any(k in c[1].lower() for k in ['title', 'bio', 'tag', 'name'])]
print(text_cols)

small[text_cols].head(10)

# check official split column
print(tracks[('set', 'split')].value_counts())

# check artist leakage risk
artist_counts = small[('artist', 'name')].value_counts()
print(f"\nUnique artists in fma_small: {small[('artist','name')].nunique()}")
print(f"Tracks: {len(small)}")
print(artist_counts.head(10))

small = small.copy()
small['split'] = tracks.loc[small.index, ('set', 'split')]
small['artist_name'] = tracks.loc[small.index, ('artist', 'name')]

train_artists = set(small[small['split'] == 'training']['artist_name'])
val_artists   = set(small[small['split'] == 'validation']['artist_name'])
test_artists  = set(small[small['split'] == 'test']['artist_name'])

print("split sizes:", small['split'].value_counts().to_dict())
print("train∩val artists:", len(train_artists & val_artists))
print("train∩test artists:", len(train_artists & test_artists))
print("val∩test artists:", len(val_artists & test_artists))

#building the text field and labels for Task 1
#step 1 of task1 cleaning the bio and combined text field
import re

def clean_html(raw):
    if pd.isna(raw):
        return ""
    return re.sub(r'<[^>]+>', ' ', str(raw)).strip()

small['bio_clean'] = tracks.loc[small.index, ('artist', 'bio')].apply(clean_html)
small['album_title'] = tracks.loc[small.index, ('album', 'title')].fillna("")
small['track_title'] = tracks.loc[small.index, ('track', 'title')].fillna("")

small['text'] = (
    small['track_title'] + " by " +
    small['artist_name'] + ". Album: " +
    small['album_title'] + ". " +
    small['bio_clean']
)

small['text'] = small['text'].str.strip()

# sanity check
print(small['text'].str.len().describe())
small[['text']].head(3)

#building the label (genre_top, encoded as integer class for now — single-label 8-class, which treat as a multi-label-style BCE task per the spec by one-hot encoding)
#step2 task1
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
small['genre_label'] = le.fit_transform(small[('track', 'genre_top')])

print(dict(zip(le.classes_, range(len(le.classes_)))))
small['genre_label'].value_counts()

#step 3 task 1 spliting into train/val/test using the official split, then tokenize:
train_df = small[small['split'] == 'training'].reset_index(drop=True)
val_df   = small[small['split'] == 'validation'].reset_index(drop=True)
test_df  = small[small['split'] == 'test'].reset_index(drop=True)

print(len(train_df), len(val_df), len(test_df))

#step 4 task 1 building a PyTorch Dataset with BERT tokenization:
from torch.utils.data import Dataset, DataLoader as TorchDataLoader

MODEL_NAME = "distilbert-base-uncased"
MAX_LEN = 256

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

class TagTextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=MAX_LEN):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )
        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "label": torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_ds = TagTextDataset(train_df['text'].tolist(), train_df['genre_label'].tolist(), tokenizer)
val_ds   = TagTextDataset(val_df['text'].tolist(), val_df['genre_label'].tolist(), tokenizer)
test_ds  = TagTextDataset(test_df['text'].tolist(), test_df['genre_label'].tolist(), tokenizer)

BATCH_SIZE = 16
train_loader = TorchDataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = TorchDataLoader(val_ds, batch_size=BATCH_SIZE)
test_loader  = TorchDataLoader(test_ds, batch_size=BATCH_SIZE)

print("Batches:", len(train_loader), len(val_loader), len(test_loader))

#Step 5 task 1 — model class (BERT + classification head):
class BertTagClassifier(nn.Module):
    def __init__(self, model_name=MODEL_NAME, num_classes=8, dropout=0.3):
        super().__init__()
        self.bert = AutoModel.from_pretrained(model_name)
        hidden_size = self.bert.config.hidden_size
        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Linear(hidden_size, num_classes)

    def forward(self, input_ids, attention_mask):
        out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_token = out.last_hidden_state[:, 0, :]  # CLS token, t = BERT_CLS(X_text)
        cls_token = self.dropout(cls_token)
        logits = self.classifier(cls_token)  # Wt + b
        return logits

model = BertTagClassifier().to(device)
print(sum(p.numel() for p in model.parameters() if p.requires_grad), "trainable params")

#Step 6 task1 — training loop with Macro-F1/Micro-F1 tracking per epoch
from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()  # single-label genre_top; note in report this substitutes multi-label BCE per FMA's tag sparsity

EPOCHS = 4
history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}

def evaluate(loader):
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)
            logits = model(input_ids, attention_mask)
            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    macro_f1 = f1_score(all_labels, all_preds, average="macro")
    micro_f1 = f1_score(all_labels, all_preds, average="micro")
    return macro_f1, micro_f1, all_preds, all_labels

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()
        logits = model(input_ids, attention_mask)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    val_macro_f1, val_micro_f1, _, _ = evaluate(val_loader)

    history["train_loss"].append(avg_loss)
    history["val_macro_f1"].append(val_macro_f1)
    history["val_micro_f1"].append(val_micro_f1)

    print(f"Epoch {epoch+1}: loss={avg_loss:.4f}  val_macro_f1={val_macro_f1:.4f}  val_micro_f1={val_micro_f1:.4f}")

clean = pd.DataFrame({
    "text": small["text"].values,
    "genre_label": small["genre_label"].values,
    "split": small["split"].values,
}, index=small.index)

train_df = clean[clean['split'] == 'training'].reset_index(drop=True)
val_df   = clean[clean['split'] == 'validation'].reset_index(drop=True)
test_df  = clean[clean['split'] == 'test'].reset_index(drop=True)

print(len(train_df), len(val_df), len(test_df))

#step 7 task1 plotting F1 curves over epochs:
plt.figure(figsize=(7,5))
epochs_range = range(1, EPOCHS+1)
plt.plot(epochs_range, history["val_macro_f1"], marker='o', label="Val Macro-F1")
plt.plot(epochs_range, history["val_micro_f1"], marker='o', label="Val Micro-F1")
plt.xlabel("Epoch")
plt.ylabel("F1 Score")
plt.title("Task 1: BERT Tag Classifier — Validation F1 vs Epoch")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig("/content/gnn-bert-music-context/results/plots/task1_f1_curves.png", dpi=150, bbox_inches="tight")
plt.show()

#Step 8 task 1 final test set evaluation
test_macro_f1, test_micro_f1, test_preds, test_labels = evaluate(test_loader)
test_precision = precision_score(test_labels, test_preds, average="macro")
test_recall = recall_score(test_labels, test_preds, average="macro")

print(f"TEST — Macro-F1: {test_macro_f1:.4f}  Micro-F1: {test_micro_f1:.4f}")
print(f"TEST — Macro-Precision: {test_precision:.4f}  Macro-Recall: {test_recall:.4f}")

#Step 9 task 1 5 example predictions
model.eval()
sample_idx = np.random.choice(len(test_df), 5, replace=False)

for i in sample_idx:
    text = test_df.iloc[i]['text']
    true_label = le.classes_[test_df.iloc[i]['genre_label']]

    enc = tokenizer(text, truncation=True, padding="max_length", max_length=MAX_LEN, return_tensors="pt").to(device)
    with torch.no_grad():
        logits = model(enc["input_ids"], enc["attention_mask"])
        pred_label = le.classes_[torch.argmax(logits, dim=1).item()]

    print(f"True: {true_label:15s} | Pred: {pred_label:15s} | Text: {text[:100]}...")
    print("-"*100)

#step 10 task 1 saving metrics + predictions to results/
import json

metrics = {
    "task": "Task 1: BERT Tag/Genre Classifier",
    "model": MODEL_NAME,
    "epochs": EPOCHS,
    "history": history,
    "test_macro_f1": test_macro_f1,
    "test_micro_f1": test_micro_f1,
    "test_macro_precision": test_precision,
    "test_macro_recall": test_recall,
}

with open("/content/gnn-bert-music-context/results/task1_metrics.json", "w") as f:
    json.dump(metrics, f, indent=2)

print("Saved metrics.")

#step 11 saving the model weights
torch.save(model.state_dict(), "/content/gnn-bert-music-context/results/task1_bert_model.pt")
print("Model saved.")

#task2
#step1 — build the balanced subsample with audio paths:
import librosa
import numpy as np

N_PER_GENRE = 250  # ~250*8 = 2000 tracks total

clean['genre_top'] = tracks.loc[small.index, ('track', 'genre_top')].values
clean['track_id'] = small.index

def track_id_to_path(track_id):
    tid_str = f"{track_id:06d}"
    return f"/content/gnn-bert-music-context/data/raw/fma_small/{tid_str[:3]}/{tid_str}.mp3"

clean['audio_path'] = clean['track_id'].apply(track_id_to_path)

sampled = (
    clean.groupby('genre_top', group_keys=False)
    .apply(lambda g: g.sample(n=min(N_PER_GENRE, len(g)), random_state=SEED))
    .reset_index(drop=True)
)

print(sampled['genre_top'].value_counts())
print(sampled['split'].value_counts())

#task2
#step2—quick sanity check that files actually exist and load
import os

missing = 0
broken = 0
for path in sampled['audio_path'].head(20):
    if not os.path.exists(path):
        missing += 1
        continue
    try:
        y, sr = librosa.load(path, sr=22050, duration=1.0)
    except Exception as e:
        broken += 1

print(f"Checked 20 files — missing: {missing}, broken: {broken}")

#task 2 step 3 chrome extraction function
SR = 22050
SEGMENT_SEC = 5.0
MAX_DURATION = 30.0  # FMA-small clips are ~30s; cap to keep this bounded

def extract_segment_chroma(path, sr=SR, segment_sec=SEGMENT_SEC, max_duration=MAX_DURATION):
    try:
        y, _ = librosa.load(path, sr=sr, duration=max_duration)
    except Exception:
        return None

    if len(y) < sr:  # too short to be usable
        return None

    seg_len = int(segment_sec * sr)
    n_segments = len(y) // seg_len
    if n_segments < 2:  # need at least 2 nodes for a graph
        return None

    segment_features = []
    for i in range(n_segments):
        seg = y[i * seg_len : (i + 1) * seg_len]
        chroma = librosa.feature.chroma_stft(y=seg, sr=sr)
        chroma_mean = chroma.mean(axis=1)  # 12-dim, averaged over time
        segment_features.append(chroma_mean)

    return np.stack(segment_features)  # shape: (n_segments, 12)

# quick test on one file
test_feat = extract_segment_chroma(sampled['audio_path'].iloc[0])
print("Shape:", test_feat.shape if test_feat is not None else None)

#Step 4 — build graph for one track (nodes = segments, edges = temporal + similarity):
from sklearn.metrics.pairwise import cosine_similarity

SIM_THRESHOLD = 0.9  # cosine similarity threshold for extra edges

def build_segment_graph(chroma_feats, label, sim_threshold=SIM_THRESHOLD):
    n = chroma_feats.shape[0]
    x = torch.tensor(chroma_feats, dtype=torch.float)

    edge_list = []

    # temporal adjacency: i <-> i+1
    for i in range(n - 1):
        edge_list.append([i, i + 1])
        edge_list.append([i + 1, i])

    # similarity edges: cosine sim > threshold (excluding self and already-adjacent)
    sim_matrix = cosine_similarity(chroma_feats)
    for i in range(n):
        for j in range(i + 1, n):
            if j != i + 1 and sim_matrix[i, j] > sim_threshold:
                edge_list.append([i, j])
                edge_list.append([j, i])

    edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous()

    y = torch.tensor([label], dtype=torch.long)

    return Data(x=x, edge_index=edge_index, y=y)

# test on the same file
test_graph = build_segment_graph(test_feat, label=0)
print(test_graph)
print("Num nodes:", test_graph.num_nodes, "Num edges:", test_graph.num_edges)

#task 2 Step 5 — full extraction loop (this is the slow part, ~10–15 min for 2000 tracks):
graphs = []
labels_used = []
failed = 0

genre_to_idx = {g: i for i, g in enumerate(sorted(sampled['genre_top'].unique()))}
print(genre_to_idx)

for idx, row in tqdm(sampled.iterrows(), total=len(sampled)):
    chroma_feat = extract_segment_chroma(row['audio_path'])
    if chroma_feat is None:
        failed += 1
        continue

    label = genre_to_idx[row['genre_top']]
    graph = build_segment_graph(chroma_feat, label)
    graph.split = row['split']  # tag for later splitting
    graph.track_id = row['track_id']
    graphs.append(graph)

print(f"\nBuilt {len(graphs)} graphs, {failed} failed/skipped")

#task2 Step 6 — split graphs and save example graphs to disk:
train_graphs = [g for g in graphs if g.split == 'training']
val_graphs   = [g for g in graphs if g.split == 'validation']
test_graphs  = [g for g in graphs if g.split == 'test']

print(f"Train: {len(train_graphs)}  Val: {len(val_graphs)}  Test: {len(test_graphs)}")

# save 25 example graphs as required deliverable
GRAPH_DIR = "/content/gnn-bert-music-context/data/graphs"
os.makedirs(GRAPH_DIR, exist_ok=True)

for i, g in enumerate(graphs[:25]):
    torch.save(g, f"{GRAPH_DIR}/example_graph_{i:02d}_track{g.track_id}.pt")

print("Saved 25 example graphs to", GRAPH_DIR)

# also save the full graph list for training (so we don't need to re-extract if runtime hiccups)
torch.save(graphs, f"{GRAPH_DIR}/all_graphs.pt")
print("Saved full graph set.")

#task 2 step 7
from torch_geometric.loader import DataLoader as PyGDataLoader

GRAPH_BATCH_SIZE = 32

train_graph_loader = PyGDataLoader(train_graphs, batch_size=GRAPH_BATCH_SIZE, shuffle=True)
val_graph_loader   = PyGDataLoader(val_graphs, batch_size=GRAPH_BATCH_SIZE)
test_graph_loader  = PyGDataLoader(test_graphs, batch_size=GRAPH_BATCH_SIZE)

print("Batches:", len(train_graph_loader), len(val_graph_loader), len(test_graph_loader))

#task 2 Step 8 — GraphSAGE model class:
class GraphSAGEClassifier(nn.Module):
    def __init__(self, in_channels=12, hidden_channels=64, num_layers=3, num_classes=8, dropout=0.3):
        super().__init__()
        self.sage = GraphSAGE(
            in_channels=in_channels,
            hidden_channels=hidden_channels,
            num_layers=num_layers,
            dropout=dropout,
        )
        self.classifier = nn.Linear(hidden_channels, num_classes)

    def forward(self, x, edge_index, batch):
        h = self.sage(x, edge_index)          # node embeddings after L layers
        g = global_mean_pool(h, batch)        # mean-pool readout -> graph embedding
        logits = self.classifier(g)           # Wg + b
        return logits

gnn_model = GraphSAGEClassifier().to(device)
print(sum(p.numel() for p in gnn_model.parameters() if p.requires_grad), "trainable params")

#task 2 Step 9 — training loop (mirrors Task 1's structure for consistent reporting):
gnn_optimizer = AdamW(gnn_model.parameters(), lr=1e-3)
gnn_criterion = nn.CrossEntropyLoss()

GNN_EPOCHS = 30
gnn_history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}

def evaluate_gnn(loader):
    gnn_model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for batch in loader:
            batch = batch.to(device)
            logits = gnn_model(batch.x, batch.edge_index, batch.batch)
            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch.y.cpu().numpy())
    macro_f1 = f1_score(all_labels, all_preds, average="macro")
    micro_f1 = f1_score(all_labels, all_preds, average="micro")
    return macro_f1, micro_f1

for epoch in range(GNN_EPOCHS):
    gnn_model.train()
    total_loss = 0
    for batch in train_graph_loader:
        batch = batch.to(device)
        gnn_optimizer.zero_grad()
        logits = gnn_model(batch.x, batch.edge_index, batch.batch)
        loss = gnn_criterion(logits, batch.y)
        loss.backward()
        gnn_optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_graph_loader)
    val_macro_f1, val_micro_f1 = evaluate_gnn(val_graph_loader)

    gnn_history["train_loss"].append(avg_loss)
    gnn_history["val_macro_f1"].append(val_macro_f1)
    gnn_history["val_micro_f1"].append(val_micro_f1)

    if (epoch + 1) % 5 == 0 or epoch == 0:
        print(f"Epoch {epoch+1}: loss={avg_loss:.4f}  val_macro_f1={val_macro_f1:.4f}  val_micro_f1={val_micro_f1:.4f}")

#task 2 Step 10 — final GNN test evaluation + save results:
gnn_test_macro_f1, gnn_test_micro_f1 = evaluate_gnn(test_graph_loader)
print(f"GNN TEST — Macro-F1: {gnn_test_macro_f1:.4f}  Micro-F1: {gnn_test_micro_f1:.4f}")

gnn_metrics = {
    "task": "Task 2: GraphSAGE on Segment Chroma Graphs",
    "epochs": GNN_EPOCHS,
    "history": gnn_history,
    "test_macro_f1": gnn_test_macro_f1,
    "test_micro_f1": gnn_test_micro_f1,
}

with open("/content/gnn-bert-music-context/results/task2_gnn_metrics.json", "w") as f:
    json.dump(gnn_metrics, f, indent=2)

torch.save(gnn_model.state_dict(), "/content/gnn-bert-music-context/results/task2_gnn_model.pt")

plt.figure(figsize=(7,5))
plt.plot(range(1, GNN_EPOCHS+1), gnn_history["val_macro_f1"], label="Val Macro-F1")
plt.plot(range(1, GNN_EPOCHS+1), gnn_history["val_micro_f1"], label="Val Micro-F1")
plt.xlabel("Epoch")
plt.ylabel("F1 Score")
plt.title("Task 2: GraphSAGE — Validation F1 vs Epoch")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig("/content/gnn-bert-music-context/results/plots/task2_f1_curves.png", dpi=150, bbox_inches="tight")
plt.show()

#task 2 Step 11 — mel-spectrogram extraction (fixed-size, so it can go straight into a CNN):
N_MELS = 64
FIXED_FRAMES = 130  # ~ corresponds to ~3s at hop_length=512, sr=22050; we'll pad/crop to this

def extract_melspec(path, sr=SR, n_mels=N_MELS, fixed_frames=FIXED_FRAMES, duration=MAX_DURATION):
    try:
        y, _ = librosa.load(path, sr=sr, duration=duration)
    except Exception:
        return None
    if len(y) < sr:
        return None

    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels)
    mel_db = librosa.power_to_db(mel, ref=np.max)

    # pad or crop time axis to fixed_frames
    if mel_db.shape[1] < fixed_frames:
        pad_width = fixed_frames - mel_db.shape[1]
        mel_db = np.pad(mel_db, ((0,0),(0,pad_width)), mode='constant', constant_values=mel_db.min())
    else:
        mel_db = mel_db[:, :fixed_frames]

    return mel_db  # shape: (n_mels, fixed_frames)

test_mel = extract_melspec(sampled['audio_path'].iloc[0])
print("Shape:", test_mel.shape)

#task 2 Step 12 — full mel-spec extraction (reuses the same sampled tracks/labels for a fair, apples-to-apples comparison with the GNN):
mel_specs = []
mel_labels = []
mel_splits = []
failed_mel = 0

for idx, row in tqdm(sampled.iterrows(), total=len(sampled)):
    mel = extract_melspec(row['audio_path'])
    if mel is None:
        failed_mel += 1
        continue
    mel_specs.append(mel)
    mel_labels.append(genre_to_idx[row['genre_top']])
    mel_splits.append(row['split'])

mel_specs = np.stack(mel_specs)  # (N, 64, 130)
mel_labels = np.array(mel_labels)
mel_splits = np.array(mel_splits)

print(f"Built {len(mel_specs)} mel-specs, {failed_mel} failed")
print("Mel array shape:", mel_specs.shape)

# save for reproducibility
np.save("/content/gnn-bert-music-context/data/features/mel_specs.npy", mel_specs)
np.save("/content/gnn-bert-music-context/data/features/mel_labels.npy", mel_labels)
np.save("/content/gnn-bert-music-context/data/features/mel_splits.npy", mel_splits)

#task 2 Step 13 — CNN model (simple 2D conv stack over mel-spectrograms, standard baseline architecture):
class MelCNN(nn.Module):
    def __init__(self, num_classes=8):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((4, 4)),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 4 * 4, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes),
        )

    def forward(self, x):
        x = self.conv(x)
        return self.classifier(x)

cnn_model = MelCNN().to(device)
print(sum(p.numel() for p in cnn_model.parameters() if p.requires_grad), "trainable params")

#task 2 Step 14 — build tensors/dataloaders and normalize:
from torch.utils.data import TensorDataset

# normalize mel specs (z-score using train stats only, avoid leakage)
train_mask = mel_splits == 'training'
mel_mean = mel_specs[train_mask].mean()
mel_std = mel_specs[train_mask].std()

mel_specs_norm = (mel_specs - mel_mean) / mel_std
mel_tensor = torch.tensor(mel_specs_norm, dtype=torch.float).unsqueeze(1)  # (N, 1, 64, 130)
label_tensor = torch.tensor(mel_labels, dtype=torch.long)

train_idx = np.where(mel_splits == 'training')[0]
val_idx   = np.where(mel_splits == 'validation')[0]
test_idx  = np.where(mel_splits == 'test')[0]

cnn_train_ds = TensorDataset(mel_tensor[train_idx], label_tensor[train_idx])
cnn_val_ds   = TensorDataset(mel_tensor[val_idx], label_tensor[val_idx])
cnn_test_ds  = TensorDataset(mel_tensor[test_idx], label_tensor[test_idx])

cnn_train_loader = TorchDataLoader(cnn_train_ds, batch_size=32, shuffle=True)
cnn_val_loader   = TorchDataLoader(cnn_val_ds, batch_size=32)
cnn_test_loader  = TorchDataLoader(cnn_test_ds, batch_size=32)

print("Batches:", len(cnn_train_loader), len(cnn_val_loader), len(cnn_test_loader))

#task 2 Step 15 — CNN training loop (same structure as before, for consistent reporting):
cnn_optimizer = AdamW(cnn_model.parameters(), lr=1e-3)
cnn_criterion = nn.CrossEntropyLoss()

CNN_EPOCHS = 30
cnn_history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}

def evaluate_cnn(loader):
    cnn_model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for x_batch, y_batch in loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            logits = cnn_model(x_batch)
            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(y_batch.cpu().numpy())
    macro_f1 = f1_score(all_labels, all_preds, average="macro")
    micro_f1 = f1_score(all_labels, all_preds, average="micro")
    return macro_f1, micro_f1

for epoch in range(CNN_EPOCHS):
    cnn_model.train()
    total_loss = 0
    for x_batch, y_batch in cnn_train_loader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)
        cnn_optimizer.zero_grad()
        logits = cnn_model(x_batch)
        loss = cnn_criterion(logits, y_batch)
        loss.backward()
        cnn_optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(cnn_train_loader)
    val_macro_f1, val_micro_f1 = evaluate_cnn(cnn_val_loader)

    cnn_history["train_loss"].append(avg_loss)
    cnn_history["val_macro_f1"].append(val_macro_f1)
    cnn_history["val_micro_f1"].append(val_micro_f1)

    if (epoch + 1) % 5 == 0 or epoch == 0:
        print(f"Epoch {epoch+1}: loss={avg_loss:.4f}  val_macro_f1={val_macro_f1:.4f}  val_micro_f1={val_micro_f1:.4f}")

#Step 15b — retrain with checkpointing (same as before, just adds a torch.save when val improves):
cnn_model = MelCNN().to(device)  # reinit
cnn_optimizer = AdamW(cnn_model.parameters(), lr=1e-3)

best_val_f1 = 0
cnn_history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}
CKPT_PATH = "/content/gnn-bert-music-context/results/task2_cnn_best.pt"

for epoch in range(CNN_EPOCHS):
    cnn_model.train()
    total_loss = 0
    for x_batch, y_batch in cnn_train_loader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)
        cnn_optimizer.zero_grad()
        logits = cnn_model(x_batch)
        loss = cnn_criterion(logits, y_batch)
        loss.backward()
        cnn_optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(cnn_train_loader)
    val_macro_f1, val_micro_f1 = evaluate_cnn(cnn_val_loader)

    cnn_history["train_loss"].append(avg_loss)
    cnn_history["val_macro_f1"].append(val_macro_f1)
    cnn_history["val_micro_f1"].append(val_micro_f1)

    if val_macro_f1 > best_val_f1:
        best_val_f1 = val_macro_f1
        torch.save(cnn_model.state_dict(), CKPT_PATH)

    if (epoch + 1) % 5 == 0 or epoch == 0:
        print(f"Epoch {epoch+1}: loss={avg_loss:.4f}  val_macro_f1={val_macro_f1:.4f}  val_micro_f1={val_micro_f1:.4f}")

print(f"\nBest val Macro-F1: {best_val_f1:.4f}")

#task 2 Step 16 — load best checkpoint, evaluate on test, save results/plots:
cnn_model.load_state_dict(torch.load(CKPT_PATH))
cnn_test_macro_f1, cnn_test_micro_f1 = evaluate_cnn(cnn_test_loader)
print(f"CNN TEST (best ckpt) — Macro-F1: {cnn_test_macro_f1:.4f}  Micro-F1: {cnn_test_micro_f1:.4f}")

cnn_metrics = {
    "task": "Task 2 Baseline (B2): CNN on Mel-Spectrogram",
    "epochs": CNN_EPOCHS,
    "history": cnn_history,
    "best_val_macro_f1": best_val_f1,
    "test_macro_f1": cnn_test_macro_f1,
    "test_micro_f1": cnn_test_micro_f1,
}
with open("/content/gnn-bert-music-context/results/task2_cnn_baseline_metrics.json", "w") as f:
    json.dump(cnn_metrics, f, indent=2)

plt.figure(figsize=(7,5))
plt.plot(range(1, CNN_EPOCHS+1), cnn_history["val_macro_f1"], label="Val Macro-F1")
plt.plot(range(1, CNN_EPOCHS+1), cnn_history["val_micro_f1"], label="Val Micro-F1")
plt.xlabel("Epoch")
plt.ylabel("F1 Score")
plt.title("Task 2 Baseline: CNN on Mel-Spec — Validation F1 vs Epoch")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig("/content/gnn-bert-music-context/results/plots/task2_cnn_baseline_f1_curves.png", dpi=150, bbox_inches="tight")
plt.show()

#task 3
#Step 1 — build the paired dataset (align graphs + text + labels by track_id):
# map track_id -> graph object (from the graphs list we built in Task 2)
graph_by_track = {g.track_id: g for g in graphs}

# map track_id -> text (from Task 1's `clean` dataframe)
text_by_track = dict(zip(clean['track_id'], clean['text']))

paired_data = []
for g in graphs:
    tid = g.track_id
    if tid in text_by_track:
        paired_data.append({
            "track_id": tid,
            "graph": g,
            "text": text_by_track[tid],
            "label": g.y.item(),
            "split": g.split,
        })

print(f"Paired samples: {len(paired_data)}")
print(paired_data[0]['text'][:100])
print(paired_data[0]['graph'])

#task 3 step 2 split paired data and pre-tokenize text (do this once upfront, saves repeated tokenization during training):
train_paired = [p for p in paired_data if p['split'] == 'training']
val_paired   = [p for p in paired_data if p['split'] == 'validation']
test_paired  = [p for p in paired_data if p['split'] == 'test']

print(f"Train: {len(train_paired)}  Val: {len(val_paired)}  Test: {len(test_paired)}")

def tokenize_paired(paired_list, tokenizer, max_len=MAX_LEN):
    texts = [p['text'] for p in paired_list]
    enc = tokenizer(texts, truncation=True, padding="max_length", max_length=max_len, return_tensors="pt")
    for i, p in enumerate(paired_list):
        p['input_ids'] = enc['input_ids'][i]
        p['attention_mask'] = enc['attention_mask'][i]
    return paired_list

train_paired = tokenize_paired(train_paired, tokenizer)
val_paired   = tokenize_paired(val_paired, tokenizer)
test_paired  = tokenize_paired(test_paired, tokenizer)

print("Tokenization done.")

#task 3 Step 3 — custom Dataset + collate function (batches PyG graphs via Batch.from_data_list, and stacks text tensors normally):
from torch_geometric.data import Batch as PyGBatch
from torch.utils.data import Dataset as TorchDataset

class FusionDataset(TorchDataset):
    def __init__(self, paired_list):
        self.data = paired_list

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

def fusion_collate(batch):
    graphs_batch = PyGBatch.from_data_list([item['graph'] for item in batch])
    input_ids = torch.stack([item['input_ids'] for item in batch])
    attention_mask = torch.stack([item['attention_mask'] for item in batch])
    labels = torch.tensor([item['label'] for item in batch], dtype=torch.long)
    return graphs_batch, input_ids, attention_mask, labels

FUSION_BATCH_SIZE = 16

train_fusion_loader = TorchDataLoader(FusionDataset(train_paired), batch_size=FUSION_BATCH_SIZE, shuffle=True, collate_fn=fusion_collate)
val_fusion_loader   = TorchDataLoader(FusionDataset(val_paired), batch_size=FUSION_BATCH_SIZE, collate_fn=fusion_collate)
test_fusion_loader  = TorchDataLoader(FusionDataset(test_paired), batch_size=FUSION_BATCH_SIZE, collate_fn=fusion_collate)

# quick sanity check
sample_batch = next(iter(train_fusion_loader))
g_batch, ids_batch, mask_batch, label_batch = sample_batch
print("Graph batch:", g_batch)
print("Input ids shape:", ids_batch.shape)
print("Labels shape:", label_batch.shape)

#task 3 step 4 — GNN–BERT cross-attention fusion model (per your spec's Algorithm 3):
class FusionModel(nn.Module):
    def __init__(self, bert_name=MODEL_NAME, gnn_in=12, gnn_hidden=64, gnn_layers=3, num_classes=8, dropout=0.3):
        super().__init__()
        # text encoder
        self.bert = AutoModel.from_pretrained(bert_name)
        bert_dim = self.bert.config.hidden_size

        # graph encoder
        self.sage = GraphSAGE(in_channels=gnn_in, hidden_channels=gnn_hidden, num_layers=gnn_layers, dropout=dropout)

        # project graph embedding to BERT dim for attention compatibility
        self.graph_proj = nn.Linear(gnn_hidden, bert_dim)

        # cross-attention: graph embedding attends over text token embeddings
        self.cross_attn = nn.MultiheadAttention(embed_dim=bert_dim, num_heads=4, batch_first=True)

        self.dropout = nn.Dropout(dropout)
        # z = CONCAT(g, attended_text) -> classifier
        self.classifier = nn.Linear(bert_dim * 2, num_classes)

    def forward(self, graph_batch, input_ids, attention_mask):
        # --- text branch ---
        text_out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        Htext = text_out.last_hidden_state  # (B, L, bert_dim)

        # --- graph branch ---
        node_h = self.sage(graph_batch.x, graph_batch.edge_index)
        g = global_mean_pool(node_h, graph_batch.batch)  # (B, gnn_hidden)
        g_proj = self.graph_proj(g).unsqueeze(1)  # (B, 1, bert_dim) -- query

        # --- cross attention: graph queries text tokens ---
        key_padding_mask = (attention_mask == 0)  # True where padded
        attended, _ = self.cross_attn(query=g_proj, key=Htext, value=Htext, key_padding_mask=key_padding_mask)
        attended = attended.squeeze(1)  # (B, bert_dim)

        # --- fusion ---
        z = torch.cat([g_proj.squeeze(1), attended], dim=1)  # CONCAT(g, A*Htext)
        z = self.dropout(z)
        logits = self.classifier(z)
        return logits

fusion_model = FusionModel().to(device)
print(sum(p.numel() for p in fusion_model.parameters() if p.requires_grad), "trainable params")

#task 3 Step 5 — training loop for the fusion model (same structure as before, adapted for the two-input batches):
fusion_optimizer = AdamW(fusion_model.parameters(), lr=2e-5)
fusion_criterion = nn.CrossEntropyLoss()

FUSION_EPOCHS = 4
fusion_history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}

def evaluate_fusion(loader):
    fusion_model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for g_batch, ids_batch, mask_batch, label_batch in loader:
            g_batch = g_batch.to(device)
            ids_batch = ids_batch.to(device)
            mask_batch = mask_batch.to(device)
            label_batch = label_batch.to(device)

            logits = fusion_model(g_batch, ids_batch, mask_batch)
            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(label_batch.cpu().numpy())
    macro_f1 = f1_score(all_labels, all_preds, average="macro")
    micro_f1 = f1_score(all_labels, all_preds, average="micro")
    return macro_f1, micro_f1

best_fusion_val_f1 = 0
FUSION_CKPT_PATH = "/content/gnn-bert-music-context/results/task3_fusion_best.pt"

for epoch in range(FUSION_EPOCHS):
    fusion_model.train()
    total_loss = 0
    for g_batch, ids_batch, mask_batch, label_batch in tqdm(train_fusion_loader, desc=f"Epoch {epoch+1}"):
        g_batch = g_batch.to(device)
        ids_batch = ids_batch.to(device)
        mask_batch = mask_batch.to(device)
        label_batch = label_batch.to(device)

        fusion_optimizer.zero_grad()
        logits = fusion_model(g_batch, ids_batch, mask_batch)
        loss = fusion_criterion(logits, label_batch)
        loss.backward()
        fusion_optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_fusion_loader)
    val_macro_f1, val_micro_f1 = evaluate_fusion(val_fusion_loader)

    fusion_history["train_loss"].append(avg_loss)
    fusion_history["val_macro_f1"].append(val_macro_f1)
    fusion_history["val_micro_f1"].append(val_micro_f1)

    if val_macro_f1 > best_fusion_val_f1:
        best_fusion_val_f1 = val_macro_f1
        torch.save(fusion_model.state_dict(), FUSION_CKPT_PATH)

    print(f"Epoch {epoch+1}: loss={avg_loss:.4f}  val_macro_f1={val_macro_f1:.4f}  val_micro_f1={val_micro_f1:.4f}")

#task 3 Step 6 — test evaluation with best checkpoint:
fusion_model.load_state_dict(torch.load(FUSION_CKPT_PATH))
fusion_test_macro_f1, fusion_test_micro_f1 = evaluate_fusion(test_fusion_loader)
print(f"FUSION TEST (best ckpt) — Macro-F1: {fusion_test_macro_f1:.4f}  Micro-F1: {fusion_test_micro_f1:.4f}")

#task3 Step 7 — early-concat fusion variant:
class EarlyConcatFusion(nn.Module):
    def __init__(self, bert_name=MODEL_NAME, gnn_in=12, gnn_hidden=64, gnn_layers=3, num_classes=8, dropout=0.3):
        super().__init__()
        self.bert = AutoModel.from_pretrained(bert_name)
        bert_dim = self.bert.config.hidden_size
        self.sage = GraphSAGE(in_channels=gnn_in, hidden_channels=gnn_hidden, num_layers=gnn_layers, dropout=dropout)
        self.dropout = nn.Dropout(dropout)
        # simple concat: CLS token + graph embedding, no attention
        self.classifier = nn.Linear(bert_dim + gnn_hidden, num_classes)

    def forward(self, graph_batch, input_ids, attention_mask):
        text_out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        t = text_out.last_hidden_state[:, 0, :]  # CLS token

        node_h = self.sage(graph_batch.x, graph_batch.edge_index)
        g = global_mean_pool(node_h, graph_batch.batch)

        z = torch.cat([g, t], dim=1)
        z = self.dropout(z)
        return self.classifier(z)

concat_model = EarlyConcatFusion().to(device)
print(sum(p.numel() for p in concat_model.parameters() if p.requires_grad), "trainable params")

#task 3 Step 8 — train it (identical loop structure, reused function pattern):
concat_optimizer = AdamW(concat_model.parameters(), lr=2e-5)
best_concat_val_f1 = 0
CONCAT_CKPT_PATH = "/content/gnn-bert-music-context/results/task3_earlyconcat_best.pt"
concat_history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}

def evaluate_concat(loader):
    concat_model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for g_batch, ids_batch, mask_batch, label_batch in loader:
            g_batch, ids_batch, mask_batch, label_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device), label_batch.to(device)
            logits = concat_model(g_batch, ids_batch, mask_batch)
            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(label_batch.cpu().numpy())
    return f1_score(all_labels, all_preds, average="macro"), f1_score(all_labels, all_preds, average="micro")

for epoch in range(FUSION_EPOCHS):
    concat_model.train()
    total_loss = 0
    for g_batch, ids_batch, mask_batch, label_batch in tqdm(train_fusion_loader, desc=f"Epoch {epoch+1}"):
        g_batch, ids_batch, mask_batch, label_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device), label_batch.to(device)
        concat_optimizer.zero_grad()
        logits = concat_model(g_batch, ids_batch, mask_batch)
        loss = fusion_criterion(logits, label_batch)
        loss.backward()
        concat_optimizer.step()
        total_loss += loss.item()

    val_macro_f1, val_micro_f1 = evaluate_concat(val_fusion_loader)
    concat_history["train_loss"].append(total_loss/len(train_fusion_loader))
    concat_history["val_macro_f1"].append(val_macro_f1)
    concat_history["val_micro_f1"].append(val_micro_f1)

    if val_macro_f1 > best_concat_val_f1:
        best_concat_val_f1 = val_macro_f1
        torch.save(concat_model.state_dict(), CONCAT_CKPT_PATH)

    print(f"Epoch {epoch+1}: val_macro_f1={val_macro_f1:.4f}  val_micro_f1={val_micro_f1:.4f}")

#task 3 Step 9 — test evaluation:
concat_model.load_state_dict(torch.load(CONCAT_CKPT_PATH))
concat_test_macro_f1, concat_test_micro_f1 = evaluate_concat(test_fusion_loader)
print(f"EARLY-CONCAT TEST (best ckpt) — Macro-F1: {concat_test_macro_f1:.4f}  Micro-F1: {concat_test_micro_f1:.4f}")

# save both fusion variants' metrics together
task3_metrics = {
    "task": "Task 3: GNN-BERT Fusion Ablation",
    "bert_only_test_macro_f1": test_macro_f1,       # from Task 1
    "gnn_only_test_macro_f1": gnn_test_macro_f1,    # from Task 2
    "early_concat": {
        "history": concat_history,
        "test_macro_f1": concat_test_macro_f1,
        "test_micro_f1": concat_test_micro_f1,
    },
    "cross_attention": {
        "history": fusion_history,
        "test_macro_f1": fusion_test_macro_f1,
        "test_micro_f1": fusion_test_micro_f1,
    },
}

with open("/content/gnn-bert-music-context/results/task3_ablation_metrics.json", "w") as f:
    json.dump(task3_metrics, f, indent=2)

print("Saved ablation results.")

#task 3 Step 10 — extract fused embeddings (z, pre-classifier) for t-SNE:
from sklearn.manifold import TSNE

concat_model.eval()
all_z, all_labels_tsne = [], []

with torch.no_grad():
    for g_batch, ids_batch, mask_batch, label_batch in test_fusion_loader:
        g_batch, ids_batch, mask_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device)

        text_out = concat_model.bert(input_ids=ids_batch, attention_mask=mask_batch)
        t = text_out.last_hidden_state[:, 0, :]
        node_h = concat_model.sage(g_batch.x, g_batch.edge_index)
        g = global_mean_pool(node_h, g_batch.batch)
        z = torch.cat([g, t], dim=1)

        all_z.append(z.cpu().numpy())
        all_labels_tsne.extend(label_batch.numpy())

all_z = np.concatenate(all_z, axis=0)
all_labels_tsne = np.array(all_labels_tsne)

tsne = TSNE(n_components=2, random_state=SEED, perplexity=30)
z_2d = tsne.fit_transform(all_z)

plt.figure(figsize=(9,7))
scatter = plt.scatter(z_2d[:,0], z_2d[:,1], c=all_labels_tsne, cmap='tab10', alpha=0.7)
plt.legend(handles=scatter.legend_elements()[0], labels=list(le.classes_), title="Genre", bbox_to_anchor=(1.05, 1))
plt.title("t-SNE of Fused GNN-BERT Embeddings (colored by genre)")
plt.savefig("/content/gnn-bert-music-context/results/plots/task3_tsne.png", dpi=150, bbox_inches="tight")
plt.show()

#task 3 Step 11 — find case study candidates from the test set:
concat_model.eval()
case_study_data = []

with torch.no_grad():
    for g_batch, ids_batch, mask_batch, label_batch in test_fusion_loader:
        g_batch_gpu, ids_batch_gpu, mask_batch_gpu = g_batch.to(device), ids_batch.to(device), mask_batch.to(device)
        logits = concat_model(g_batch_gpu, ids_batch_gpu, mask_batch_gpu)
        preds = torch.argmax(logits, dim=1).cpu()

        for i in range(len(label_batch)):
            case_study_data.append({
                "track_id": g_batch[i].track_id if hasattr(g_batch[i], 'track_id') else None,
                "true": le.classes_[label_batch[i].item()],
                "pred": le.classes_[preds[i].item()],
                "correct": label_batch[i].item() == preds[i].item(),
            })

# match back to track_id + text using test_paired (same order as test_fusion_loader since shuffle=False)
for i, cs in enumerate(case_study_data):
    cs["track_id"] = test_paired[i]["track_id"]
    cs["text"] = test_paired[i]["text"]

correct_cases = [c for c in case_study_data if c["correct"]]
wrong_cases = [c for c in case_study_data if not c["correct"]]

print(f"Correct: {len(correct_cases)}  Wrong: {len(wrong_cases)}")
print("\n--- Example correct case ---")
print(correct_cases[0])
print("\n--- Example wrong case (mixed genre confusion) ---")
print(wrong_cases[0])

#task 3 Step 12 — find a case matching the t-SNE mixing pattern:
mixing_genres = {'Pop', 'Electronic', 'Hip-Hop', 'Experimental'}
mixing_confusions = [c for c in wrong_cases if c['true'] in mixing_genres and c['pred'] in mixing_genres]

print(f"Confusions within the mixing cluster: {len(mixing_confusions)}")
for c in mixing_confusions[:5]:
    print(c)

#task 3 Step 13 — save the 3 case studies as your required deliverable:
case_studies = {
    "case_1_success": {
        "track_id": 63064,
        "true_genre": "Electronic",
        "predicted_genre": "Electronic",
        "text": "Underwater by Koona. Album: Underwater, Starkey. Koona è un dubstep dj & live setter e odia le bio.",
        "analysis": "Model correctly identifies Electronic via explicit genre-signaling text ('dubstep dj'), showing BERT branch effectively picks up direct genre vocabulary in bios."
    },
    "case_2_thin_text_failure": {
        "track_id": 93521,
        "true_genre": "Electronic",
        "predicted_genre": "Instrumental",
        "text": "Ivory by Moon Veil. Album: Snake Charm.",
        "analysis": "Near-empty metadata (no bio) leaves the text branch with almost no signal, and the weak GNN branch (test Macro-F1 0.24 standalone) cannot compensate. Illustrates a core limitation of using FMA bio/title text as a tag substitute rather than true tags/captions."
    },
    "case_3_genre_boundary_ambiguity": {
        "track_id": 108528,
        "true_genre": "Electronic",
        "predicted_genre": "Hip-Hop",
        "text": "Funk Therapy by Ghost By Nature... exploring the outer edges of electro, hip-hop and breaks, never stopped listening to and mixing techno...",
        "analysis": "Artist's own bio explicitly self-describes as blending electro, hip-hop, and techno. The 'incorrect' prediction reflects genuine genre ambiguity in the source material, matching the mixed Pop/Electronic/Hip-Hop/Experimental cluster observed in the t-SNE plot, rather than a model error per se."
    }
}

with open("/content/gnn-bert-music-context/results/task3_case_studies.json", "w") as f:
    json.dump(case_studies, f, indent=2)

print("Case studies saved.")

#task 4 Step 1 — load MusicCaps captions metadata:
!pip install -q datasets huggingface_hub

from datasets import load_dataset

musiccaps = load_dataset("google/MusicCaps")['train']
musiccaps_df = musiccaps.to_pandas()

print(musiccaps_df.shape)
print(musiccaps_df[['ytid', 'caption', 'aspect_list', 'is_balanced_subset']].head(3))

#task 4 Step 2 —downloading a few audio clips from the pre-extracted mirror to confirm this approach works before committing to a full batch:
from huggingface_hub import hf_hub_download

def try_download_clip(ytid, out_dir="/content/gnn-bert-music-context/data/raw/musiccaps_audio"):
    os.makedirs(out_dir, exist_ok=True)
    try:
        path = hf_hub_download(
            repo_id="nicolaus625/cmi",
            repo_type="dataset",
            filename=f"67_musicaps/MusicCaps/{ytid}.wav",
            local_dir=out_dir,
        )
        return path
    except Exception as e:
        return None

# test on 10 random clips
test_sample = musiccaps_df.sample(10, random_state=SEED)
results = [try_download_clip(ytid) for ytid in test_sample['ytid']]
success = sum(r is not None for r in results)
print(f"Successfully downloaded {success}/10 test clips")

#task 4 step 3 Step 3 — download until we hit a target count of successful pairs (400 is plenty for contrastive learning at this scale, and keeps runtime bounded):
TARGET_PAIRS = 400
shuffled_df = musiccaps_df.sample(frac=1, random_state=SEED).reset_index(drop=True)

musiccaps_pairs = []
attempted = 0

for _, row in tqdm(shuffled_df.iterrows(), total=len(shuffled_df)):
    if len(musiccaps_pairs) >= TARGET_PAIRS:
        break
    attempted += 1
    path = try_download_clip(row['ytid'])
    if path is not None:
        musiccaps_pairs.append({
            "ytid": row['ytid'],
            "caption": row['caption'],
            "audio_path": path,
        })

print(f"Attempted: {attempted}, Successful: {len(musiccaps_pairs)}")

print(f"Pairs collected so far: {len(musiccaps_pairs)}")

#task 4 Step 4 — build chroma segment graphs for these clips
MC_SEGMENT_SEC = 2.0  # 10s clip / 2s segments = 5 nodes per graph

def extract_segment_chroma_mc(path, sr=SR, segment_sec=MC_SEGMENT_SEC):
    try:
        y, _ = librosa.load(path, sr=sr)
    except Exception:
        return None
    if len(y) < sr:
        return None

    seg_len = int(segment_sec * sr)
    n_segments = len(y) // seg_len
    if n_segments < 2:
        return None

    segment_features = []
    for i in range(n_segments):
        seg = y[i * seg_len : (i + 1) * seg_len]
        chroma = librosa.feature.chroma_stft(y=seg, sr=sr)
        segment_features.append(chroma.mean(axis=1))

    return np.stack(segment_features)

# test on one
test_mc_feat = extract_segment_chroma_mc(musiccaps_pairs[0]['audio_path'])
print("Shape:", test_mc_feat.shape if test_mc_feat is not None else None)

#Step 5 — build graphs for all 400 pairs, and tokenize captions (reusing build_segment_graph and tokenizer from before):
mc_dual_data = []
mc_failed = 0

for pair in tqdm(musiccaps_pairs):
    feat = extract_segment_chroma_mc(pair['audio_path'])
    if feat is None:
        mc_failed += 1
        continue
    graph = build_segment_graph(feat, label=0)  # label unused for contrastive, placeholder
    mc_dual_data.append({
        "ytid": pair['ytid'],
        "caption": pair['caption'],
        "graph": graph,
    })

print(f"Built {len(mc_dual_data)} graph-caption pairs, {mc_failed} failed")

# tokenize captions
mc_captions = [d['caption'] for d in mc_dual_data]
mc_enc = tokenizer(mc_captions, truncation=True, padding="max_length", max_length=MAX_LEN, return_tensors="pt")
for i, d in enumerate(mc_dual_data):
    d['input_ids'] = mc_enc['input_ids'][i]
    d['attention_mask'] = mc_enc['attention_mask'][i]

print("Tokenization done.")

#task 4 Step 6 — train/test split (simple random split is fine here — MusicCaps has no artist-leakage concept the way FMA does, since it's individual clips, not albums):
random.shuffle(mc_dual_data)
split_idx = int(0.85 * len(mc_dual_data))
mc_train = mc_dual_data[:split_idx]
mc_test = mc_dual_data[split_idx:]

print(f"Train: {len(mc_train)}  Test: {len(mc_test)}")

#task 4 Step 7 — dual-encoder contrastive model (InfoNCE, per your spec's Algorithm 4):
class DualEncoder(nn.Module):
    def __init__(self, bert_name=MODEL_NAME, gnn_in=12, gnn_hidden=64, gnn_layers=3, proj_dim=128, dropout=0.2):
        super().__init__()
        self.bert = AutoModel.from_pretrained(bert_name)
        bert_dim = self.bert.config.hidden_size
        self.sage = GraphSAGE(in_channels=gnn_in, hidden_channels=gnn_hidden, num_layers=gnn_layers, dropout=dropout)

        self.text_proj = nn.Linear(bert_dim, proj_dim)
        self.graph_proj = nn.Linear(gnn_hidden, proj_dim)

    def encode_text(self, input_ids, attention_mask):
        out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        t = out.last_hidden_state[:, 0, :]
        t = self.text_proj(t)
        return F.normalize(t, dim=-1)

    def encode_graph(self, graph_batch):
        node_h = self.sage(graph_batch.x, graph_batch.edge_index)
        g = global_mean_pool(node_h, graph_batch.batch)
        g = self.graph_proj(g)
        return F.normalize(g, dim=-1)

dual_model = DualEncoder().to(device)
print(sum(p.numel() for p in dual_model.parameters() if p.requires_grad), "trainable params")

#task 4 Step 8 — collate + InfoNCE loss + training loop:
def contrastive_collate(batch):
    graphs_batch = PyGBatch.from_data_list([item['graph'] for item in batch])
    input_ids = torch.stack([item['input_ids'] for item in batch])
    attention_mask = torch.stack([item['attention_mask'] for item in batch])
    return graphs_batch, input_ids, attention_mask

CONTRASTIVE_BATCH_SIZE = 32
TEMPERATURE = 0.07

mc_train_loader = TorchDataLoader(mc_train, batch_size=CONTRASTIVE_BATCH_SIZE, shuffle=True, collate_fn=contrastive_collate)
mc_test_loader = TorchDataLoader(mc_test, batch_size=CONTRASTIVE_BATCH_SIZE, shuffle=False, collate_fn=contrastive_collate)

def info_nce_loss(g_embed, t_embed, temperature=TEMPERATURE):
    logits = g_embed @ t_embed.T / temperature  # (B, B) similarity matrix
    labels = torch.arange(logits.size(0), device=logits.device)
    loss_g2t = F.cross_entropy(logits, labels)
    loss_t2g = F.cross_entropy(logits.T, labels)
    return (loss_g2t + loss_t2g) / 2

dual_optimizer = AdamW(dual_model.parameters(), lr=2e-5)
DUAL_EPOCHS = 15
dual_history = {"train_loss": []}

for epoch in range(DUAL_EPOCHS):
    dual_model.train()
    total_loss = 0
    for g_batch, ids_batch, mask_batch in mc_train_loader:
        g_batch, ids_batch, mask_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device)
        dual_optimizer.zero_grad()

        g_embed = dual_model.encode_graph(g_batch)
        t_embed = dual_model.encode_text(ids_batch, mask_batch)

        loss = info_nce_loss(g_embed, t_embed)
        loss.backward()
        dual_optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(mc_train_loader)
    dual_history["train_loss"].append(avg_loss)
    print(f"Epoch {epoch+1}: loss={avg_loss:.4f}")

#task 4 Step 9 — retrieval evaluation (R@1, R@5, R@10, both directions, per your spec):
def compute_retrieval_metrics(loader, model, k_values=(1, 5, 10)):
    model.eval()
    all_g_embeds, all_t_embeds = [], []

    with torch.no_grad():
        for g_batch, ids_batch, mask_batch in loader:
            g_batch, ids_batch, mask_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device)
            g_embed = model.encode_graph(g_batch)
            t_embed = model.encode_text(ids_batch, mask_batch)
            all_g_embeds.append(g_embed.cpu())
            all_t_embeds.append(t_embed.cpu())

    all_g_embeds = torch.cat(all_g_embeds, dim=0)
    all_t_embeds = torch.cat(all_t_embeds, dim=0)

    sim_matrix = all_g_embeds @ all_t_embeds.T  # (N, N), row i = audio i, col j = caption j
    N = sim_matrix.size(0)

    def recall_at_k(sim, k):
        # audio -> caption: for each row, is the correct diagonal index in top-k?
        topk = sim.topk(k, dim=1).indices
        correct = (topk == torch.arange(N).unsqueeze(1)).any(dim=1)
        return correct.float().mean().item()

    results = {}
    for k in k_values:
        results[f"audio2caption_R@{k}"] = recall_at_k(sim_matrix, k)
        results[f"caption2audio_R@{k}"] = recall_at_k(sim_matrix.T, k)

    return results, sim_matrix

test_retrieval_metrics, test_sim_matrix = compute_retrieval_metrics(mc_test_loader, dual_model)
for k, v in test_retrieval_metrics.items():
    print(f"{k}: {v:.4f}")

#task 4 Step 10 — save retrieval metrics:
task4_metrics = {
    "task": "Task 4: Contrastive GNN-BERT (MusicCaps)",
    "num_pairs": len(mc_dual_data),
    "train_size": len(mc_train),
    "test_size": len(mc_test),
    "epochs": DUAL_EPOCHS,
    "train_loss_history": dual_history["train_loss"],
    "retrieval_metrics": test_retrieval_metrics,
}
with open("/content/gnn-bert-music-context/results/task4_contrastive_metrics.json", "w") as f:
    json.dump(task4_metrics, f, indent=2)

torch.save(dual_model.state_dict(), "/content/gnn-bert-music-context/results/task4_dual_encoder.pt")
print("Saved.")

#task 4 Step 11 — 10 qualitative retrieval examples (query caption → top-3 matched clips), required deliverable:
test_ytids = [d['ytid'] for d in mc_test]
test_captions = [d['caption'] for d in mc_test]

retrieval_examples = []
num_queries = min(10, len(test_ytids))

for i in range(num_queries):
    # caption i -> top 3 audio matches (row i of sim_matrix.T since caption->audio)
    sims = test_sim_matrix[:, i]  # column i = similarity of all audio to caption i
    top3_idx = sims.topk(3).indices.tolist()

    retrieval_examples.append({
        "query_caption": test_captions[i][:150],
        "top3_matched_ytids": [test_ytids[j] for j in top3_idx],
        "correct_match_rank": (sims.argsort(descending=True) == i).nonzero().item() + 1,
    })

for ex in retrieval_examples:
    print(f"Query: {ex['query_caption']}...")
    print(f"Top-3 matches: {ex['top3_matched_ytids']}")
    print(f"Correct match rank: {ex['correct_match_rank']}")
    print("-"*80)

with open("/content/gnn-bert-music-context/results/task4_retrieval_examples.json", "w") as f:
    json.dump(retrieval_examples, f, indent=2)

#task 4 Step 12 — zero-shot tag prediction from captions vs. Task 3 supervised model (required comparison):
genre_prompts = [f"This is a {g.lower()} music track." for g in le.classes_]
genre_enc = tokenizer(genre_prompts, truncation=True, padding="max_length", max_length=MAX_LEN, return_tensors="pt").to(device)

dual_model.eval()
with torch.no_grad():
    genre_text_embeds = dual_model.encode_text(genre_enc['input_ids'], genre_enc['attention_mask'])

    zero_shot_preds, zero_shot_labels = [], []
    for g in test_graphs:  # from Task 2, FMA test graphs with genre labels
        g_single = PyGBatch.from_data_list([g]).to(device)
        g_embed = dual_model.encode_graph(g_single)
        sims = g_embed @ genre_text_embeds.T
        pred = sims.argmax(dim=1).item()
        zero_shot_preds.append(pred)
        zero_shot_labels.append(g.y.item())

zero_shot_macro_f1 = f1_score(zero_shot_labels, zero_shot_preds, average="macro")
print(f"Zero-shot (MusicCaps-trained) Macro-F1 on FMA genre: {zero_shot_macro_f1:.4f}")
print(f"Task 3 supervised (early-concat) Macro-F1: {concat_test_macro_f1:.4f}")

task4_metrics["zero_shot_macro_f1"] = zero_shot_macro_f1
task4_metrics["task3_supervised_macro_f1"] = concat_test_macro_f1
task4_metrics["note"] = "Retrieval shows above-chance but weak alignment; embedding space shows partial collapse across queries, likely due to limited chroma graph signal and small training scale (400 pairs, 15 epochs). Zero-shot transfer to FMA genre underperforms random chance, motivating supervised fusion (Task 3) over pure contrastive transfer at this scale."

with open("/content/gnn-bert-music-context/results/task4_contrastive_metrics.json", "w") as f:
    json.dump(task4_metrics, f, indent=2)
print("Final Task 4 metrics saved.")

#AUC-PR for Task 1 (BERT):
from sklearn.preprocessing import label_binarize
def compute_auc_pr(model_fn, loader, num_classes=8):
    all_labels, all_probs = [], []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)
            logits = model(input_ids, attention_mask)
            probs = F.softmax(logits, dim=1)
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
    y_true_bin = label_binarize(all_labels, classes=list(range(num_classes)))
    return average_precision_score(y_true_bin, np.array(all_probs), average="macro")

model.eval()
task1_auc_pr = compute_auc_pr(model, test_loader)
print(f"Task 1 Test AUC-PR: {task1_auc_pr:.4f}")
from sklearn.preprocessing import label_binarize

def compute_auc_pr(model_fn, loader, num_classes=8):
    all_labels, all_probs = [], []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)
            logits = model(input_ids, attention_mask)
            probs = F.softmax(logits, dim=1)
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
    y_true_bin = label_binarize(all_labels, classes=list(range(num_classes)))
    return average_precision_score(y_true_bin, np.array(all_probs), average="macro")

model.eval()
task1_auc_pr = compute_auc_pr(model, test_loader)
print(f"Task 1 Test AUC-PR: {task1_auc_pr:.4f}")

#AUC-PR for Task 2 (GNN + CNN):
def compute_auc_pr_gnn(model_fn, loader, num_classes=8):
    all_labels, all_probs = [], []
    with torch.no_grad():
        for batch in loader:
            batch = batch.to(device)
            logits = model_fn(batch.x, batch.edge_index, batch.batch)
            probs = F.softmax(logits, dim=1)
            all_labels.extend(batch.y.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
    y_true_bin = label_binarize(all_labels, classes=list(range(num_classes)))
    return average_precision_score(y_true_bin, np.array(all_probs), average="macro")

gnn_model.eval()
task2_gnn_auc_pr = compute_auc_pr_gnn(lambda x, e, b: gnn_model(x, e, b), test_graph_loader)
print(f"Task 2 GNN Test AUC-PR: {task2_gnn_auc_pr:.4f}")

def compute_auc_pr_cnn(loader, num_classes=8):
    all_labels, all_probs = [], []
    with torch.no_grad():
        for x_batch, y_batch in loader:
            x_batch = x_batch.to(device)
            logits = cnn_model(x_batch)
            probs = F.softmax(logits, dim=1)
            all_labels.extend(y_batch.numpy())
            all_probs.extend(probs.cpu().numpy())
    y_true_bin = label_binarize(all_labels, classes=list(range(num_classes)))
    return average_precision_score(y_true_bin, np.array(all_probs), average="macro")

cnn_model.eval()
task2_cnn_auc_pr = compute_auc_pr_cnn(cnn_test_loader)
print(f"Task 2 CNN Test AUC-PR: {task2_cnn_auc_pr:.4f}")

#AUC-PR for Task 3 (both fusion variants):
def compute_auc_pr_fusion(model_fn, loader, num_classes=8):
    all_labels, all_probs = [], []
    with torch.no_grad():
        for g_batch, ids_batch, mask_batch, label_batch in loader:
            g_batch, ids_batch, mask_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device)
            logits = model_fn(g_batch, ids_batch, mask_batch)
            probs = F.softmax(logits, dim=1)
            all_labels.extend(label_batch.numpy())
            all_probs.extend(probs.cpu().numpy())
    y_true_bin = label_binarize(all_labels, classes=list(range(num_classes)))
    return average_precision_score(y_true_bin, np.array(all_probs), average="macro")

fusion_model.eval()
task3_crossattn_auc_pr = compute_auc_pr_fusion(fusion_model, test_fusion_loader)
print(f"Task 3 Cross-Attention Test AUC-PR: {task3_crossattn_auc_pr:.4f}")

concat_model.eval()
task3_concat_auc_pr = compute_auc_pr_fusion(concat_model, test_fusion_loader)
print(f"Task 3 Early-Concat Test AUC-PR: {task3_concat_auc_pr:.4f}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/README.md
# # GNN-Based BERT for Understanding Context from Music
# 
# CSE425 / EEE474 / CSE715 — Neural Networks Course Project
# ## Overview
# A hybrid BERT + Graph Neural Network (GNN) system for understanding musical
# context, implemented across four tasks of increasing complexity:
# 
# 1. Task 1 — BERT baseline: text/metadata classifier over FMA track metadata (genre proxy for tags)
# 2. Task 2 — GNN on audio structure: GraphSAGE over chroma segment graphs, compared against a CNN mel-spectrogram baseline
# 3. Task 3 — GNN-BERT fusion: cross-attention and early-concat fusion variants, full 4-way ablation
# 4. Task 4 — Contrastive retrieval: dual-encoder InfoNCE training on MusicCaps, with zero-shot genre transfer evaluation
# 
# ## Results Summary
# 
# Task1: Model: BERT-only; Test Macro-F1:	0.532; Test AUC-PR:0.575
# Task2: Model: GraphSAGE (GNN-only); Test Macro-F1: 0.238; Test AUC-PR:0.256
# Task2: Model: CNN (mel-spectrogram baseline); Test Macro-F1: 0.3817; Test AUC-PR:0.444
# Task3: Model: Cross-attention fusion; Test Macro-F1: 0.485; Test AUC-PR: 0.579
# Task3: Model: Early-concat fusion (Best); Test Macro-F1: 0.576; Test AUC-PR: 0.622
# Task4: Model: Zero-shot genre transfer; Test Macro-F1: 0.107
# 
# Retrieval (Task 4, N=60 test pairs): Audio→Caption R@10 = 26.7%, Caption→Audio R@10 = 31.7% (chance = 16.7%).
# 
# ## Datasets
# 
# - FMA-small (8,000 tracks, 8 genres): https://github.com/mdeff/fma — a balanced 2,000-track subsample was used for Tasks 2–3.
# - MusicCaps (5,521 caption pairs): https://huggingface.co/datasets/google/MusicCaps — audio retrieved via a pre-extracted community mirror ('nicolaus625/cmi'); 400 successfully paired examples used for Task 4.
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/requirements.txt
# torch>=2.11.0
# torch-geometric>=2.8.0
# transformers>=4.40.0
# librosa>=0.10.0
# datasets>=2.19.0
# huggingface_hub>=0.23.0
# scikit-learn>=1.4.0
# pandas>=2.2.0
# numpy>=1.26.0
# matplotlib>=3.8.0
# seaborn>=0.13.0
# tqdm>=4.66.0
# pyyaml>=6.0

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/.gitignore
# data/raw/
# __pycache__/
# .ipynb_checkpoints/
# *.zip
# results/task1_bert_model.pt
# results/task3_fusion_best.pt
# results/task3_earlyconcat_best.pt
# results/task4_dual_encoder.pt

!ls -la /content/gnn-bert-music-context/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/audio_features.py
# """Audio loading and feature extraction: mel-spectrograms and chroma segmentation."""
# import numpy as np
# import librosa
# 
# SR = 22050
# SEGMENT_SEC = 5.0
# MAX_DURATION = 30.0       # FMA-small clips are ~30s
# MC_SEGMENT_SEC = 2.0      # MusicCaps clips are ~10s -> 2s segments = 5 nodes
# N_MELS = 64
# FIXED_FRAMES = 130
# 
# 
# def track_id_to_path(track_id, fma_dir="/content/gnn-bert-music-context/data/raw/fma_small"):
#     """Map an FMA track_id to its mp3 path (FMA's zero-padded 3-level folder scheme)."""
#     tid_str = f"{track_id:06d}"
#     return f"{fma_dir}/{tid_str[:3]}/{tid_str}.mp3"
# 
# 
# def extract_segment_chroma(path, sr=SR, segment_sec=SEGMENT_SEC, max_duration=MAX_DURATION):
#     """Split an FMA track into fixed windows and extract mean chroma per segment.
#     Returns array of shape (n_segments, 12), or None if too short / unreadable."""
#     try:
#         y, _ = librosa.load(path, sr=sr, duration=max_duration)
#     except Exception:
#         return None
#     if len(y) < sr:
#         return None
# 
#     seg_len = int(segment_sec * sr)
#     n_segments = len(y) // seg_len
#     if n_segments < 2:  # need at least 2 nodes for a graph
#         return None
# 
#     segment_features = []
#     for i in range(n_segments):
#         seg = y[i * seg_len: (i + 1) * seg_len]
#         chroma = librosa.feature.chroma_stft(y=seg, sr=sr)
#         segment_features.append(chroma.mean(axis=1))
#     return np.stack(segment_features)
# 
# 
# def extract_segment_chroma_mc(path, sr=SR, segment_sec=MC_SEGMENT_SEC):
#     """Same as extract_segment_chroma, tuned for shorter MusicCaps clips."""
#     try:
#         y, _ = librosa.load(path, sr=sr)
#     except Exception:
#         return None
#     if len(y) < sr:
#         return None
# 
#     seg_len = int(segment_sec * sr)
#     n_segments = len(y) // seg_len
#     if n_segments < 2:
#         return None
# 
#     segment_features = []
#     for i in range(n_segments):
#         seg = y[i * seg_len: (i + 1) * seg_len]
#         chroma = librosa.feature.chroma_stft(y=seg, sr=sr)
#         segment_features.append(chroma.mean(axis=1))
#     return np.stack(segment_features)
# 
# 
# def extract_melspec(path, sr=SR, n_mels=N_MELS, fixed_frames=FIXED_FRAMES, duration=MAX_DURATION):
#     """Fixed-size log-mel spectrogram for the CNN baseline. Shape: (n_mels, fixed_frames)."""
#     try:
#         y, _ = librosa.load(path, sr=sr, duration=duration)
#     except Exception:
#         return None
#     if len(y) < sr:
#         return None
# 
#     mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels)
#     mel_db = librosa.power_to_db(mel, ref=np.max)
# 
#     if mel_db.shape[1] < fixed_frames:
#         pad_width = fixed_frames - mel_db.shape[1]
#         mel_db = np.pad(mel_db, ((0, 0), (0, pad_width)), mode="constant", constant_values=mel_db.min())
#     else:
#         mel_db = mel_db[:, :fixed_frames]
#     return mel_db

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/graph_builder.py
# """Build segment graphs (nodes = chroma segments, edges = temporal + similarity)."""
# import torch
# from torch_geometric.data import Data
# from sklearn.metrics.pairwise import cosine_similarity
# 
# SIM_THRESHOLD = 0.9  # cosine similarity threshold for extra similarity edges
# 
# 
# def build_segment_graph(chroma_feats, label, sim_threshold=SIM_THRESHOLD):
#     """chroma_feats: (n_segments, 12) array. Returns a PyG Data object."""
#     n = chroma_feats.shape[0]
#     x = torch.tensor(chroma_feats, dtype=torch.float)
# 
#     edge_list = []
#     # temporal adjacency: i <-> i+1
#     for i in range(n - 1):
#         edge_list.append([i, i + 1])
#         edge_list.append([i + 1, i])
# 
#     # similarity edges: cosine sim > threshold (excluding self and already-adjacent)
#     sim_matrix = cosine_similarity(chroma_feats)
#     for i in range(n):
#         for j in range(i + 1, n):
#             if j != i + 1 and sim_matrix[i, j] > sim_threshold:
#                 edge_list.append([i, j])
#                 edge_list.append([j, i])
# 
#     edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous()
#     y = torch.tensor([label], dtype=torch.long)
#     return Data(x=x, edge_index=edge_index, y=y)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/bert_encoder.py
# """Task 1: BERT text encoder / tag-classifier and its Dataset."""
# import torch
# import torch.nn as nn
# from torch.utils.data import Dataset
# from transformers import AutoTokenizer, AutoModel
# 
# MODEL_NAME = "distilbert-base-uncased"
# MAX_LEN = 256
# 
# 
# def get_tokenizer(model_name=MODEL_NAME):
#     return AutoTokenizer.from_pretrained(model_name)
# 
# 
# class TagTextDataset(Dataset):
#     """Tokenizes (text, label) pairs on the fly for the BERT tag/genre classifier."""
# 
#     def __init__(self, texts, labels, tokenizer, max_len=MAX_LEN):
#         self.texts = texts
#         self.labels = labels
#         self.tokenizer = tokenizer
#         self.max_len = max_len
# 
#     def __len__(self):
#         return len(self.texts)
# 
#     def __getitem__(self, idx):
#         enc = self.tokenizer(
#             self.texts[idx], truncation=True, padding="max_length",
#             max_length=self.max_len, return_tensors="pt",
#         )
#         return {
#             "input_ids": enc["input_ids"].squeeze(0),
#             "attention_mask": enc["attention_mask"].squeeze(0),
#             "label": torch.tensor(self.labels[idx], dtype=torch.long),
#         }
# 
# 
# class BertTagClassifier(nn.Module):
#     """t = BERT_CLS(X_text); y_hat = sigma(W t + b)  (Task 1 spec, Sec 4.1)."""
# 
#     def __init__(self, model_name=MODEL_NAME, num_classes=8, dropout=0.3):
#         super().__init__()
#         self.bert = AutoModel.from_pretrained(model_name)
#         hidden_size = self.bert.config.hidden_size
#         self.dropout = nn.Dropout(dropout)
#         self.classifier = nn.Linear(hidden_size, num_classes)
# 
#     def forward(self, input_ids, attention_mask):
#         out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
#         cls_token = out.last_hidden_state[:, 0, :]
#         cls_token = self.dropout(cls_token)
#         return self.classifier(cls_token)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/gnn_model.py
# """Task 2: GraphSAGE genre classifier, plus the CNN mel-spectrogram baseline (B2)."""
# import torch.nn as nn
# from torch_geometric.nn import GraphSAGE, global_mean_pool
# 
# 
# class GraphSAGEClassifier(nn.Module):
#     """GraphSAGE encoder + mean-pool readout + linear head (spec Sec 4.2)."""
# 
#     def __init__(self, in_channels=12, hidden_channels=64, num_layers=3, num_classes=8, dropout=0.3):
#         super().__init__()
#         self.sage = GraphSAGE(
#             in_channels=in_channels, hidden_channels=hidden_channels,
#             num_layers=num_layers, dropout=dropout,
#         )
#         self.classifier = nn.Linear(hidden_channels, num_classes)
# 
#     def forward(self, x, edge_index, batch):
#         h = self.sage(x, edge_index)
#         g = global_mean_pool(h, batch)
#         return self.classifier(g)
# 
# 
# class MelCNN(nn.Module):
#     """Baseline B2: simple 2D-conv stack over mel-spectrograms, no graph/text."""
# 
#     def __init__(self, num_classes=8):
#         super().__init__()
#         self.conv = nn.Sequential(
#             nn.Conv2d(1, 16, kernel_size=3, padding=1), nn.BatchNorm2d(16), nn.ReLU(), nn.MaxPool2d(2),
#             nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
#             nn.Conv2d(32, 64, kernel_size=3, padding=1), nn.BatchNorm2d(64), nn.ReLU(), nn.AdaptiveAvgPool2d((4, 4)),
#         )
#         self.classifier = nn.Sequential(
#             nn.Flatten(), nn.Linear(64 * 4 * 4, 128), nn.ReLU(), nn.Dropout(0.3), nn.Linear(128, num_classes),
#         )
# 
#     def forward(self, x):
#         return self.classifier(self.conv(x))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/fusion_model.py
# """Task 3: GNN-BERT fusion -- cross-attention variant and early-concat variant."""
# import torch
# import torch.nn as nn
# from torch.utils.data import Dataset as TorchDataset
# from torch_geometric.data import Batch as PyGBatch
# from torch_geometric.nn import GraphSAGE, global_mean_pool
# from transformers import AutoModel
# 
# 
# class FusionModel(nn.Module):
#     """Cross-attention fusion: graph embedding attends over BERT token embeddings
#     (spec Algorithm 3): z = CONCAT(g, A*Htext); y_hat = sigma(Wz)."""
# 
#     def __init__(self, bert_name, gnn_in=12, gnn_hidden=64, gnn_layers=3, num_classes=8, dropout=0.3):
#         super().__init__()
#         self.bert = AutoModel.from_pretrained(bert_name)
#         bert_dim = self.bert.config.hidden_size
#         self.sage = GraphSAGE(in_channels=gnn_in, hidden_channels=gnn_hidden, num_layers=gnn_layers, dropout=dropout)
#         self.graph_proj = nn.Linear(gnn_hidden, bert_dim)
#         self.cross_attn = nn.MultiheadAttention(embed_dim=bert_dim, num_heads=4, batch_first=True)
#         self.dropout = nn.Dropout(dropout)
#         self.classifier = nn.Linear(bert_dim * 2, num_classes)
# 
#     def forward(self, graph_batch, input_ids, attention_mask):
#         text_out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
#         Htext = text_out.last_hidden_state
# 
#         node_h = self.sage(graph_batch.x, graph_batch.edge_index)
#         g = global_mean_pool(node_h, graph_batch.batch)
#         g_proj = self.graph_proj(g).unsqueeze(1)
# 
#         key_padding_mask = (attention_mask == 0)
#         attended, _ = self.cross_attn(query=g_proj, key=Htext, value=Htext, key_padding_mask=key_padding_mask)
#         attended = attended.squeeze(1)
# 
#         z = torch.cat([g_proj.squeeze(1), attended], dim=1)
#         return self.classifier(self.dropout(z))
# 
# 
# class EarlyConcatFusion(nn.Module):
#     """Ablation: simple concat of graph embedding + BERT CLS token, no attention."""
# 
#     def __init__(self, bert_name, gnn_in=12, gnn_hidden=64, gnn_layers=3, num_classes=8, dropout=0.3):
#         super().__init__()
#         self.bert = AutoModel.from_pretrained(bert_name)
#         bert_dim = self.bert.config.hidden_size
#         self.sage = GraphSAGE(in_channels=gnn_in, hidden_channels=gnn_hidden, num_layers=gnn_layers, dropout=dropout)
#         self.dropout = nn.Dropout(dropout)
#         self.classifier = nn.Linear(bert_dim + gnn_hidden, num_classes)
# 
#     def forward(self, graph_batch, input_ids, attention_mask):
#         text_out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
#         t = text_out.last_hidden_state[:, 0, :]
# 
#         node_h = self.sage(graph_batch.x, graph_batch.edge_index)
#         g = global_mean_pool(node_h, graph_batch.batch)
# 
#         z = torch.cat([g, t], dim=1)
#         return self.classifier(self.dropout(z))
# 
# 
# class FusionDataset(TorchDataset):
#     """Wraps paired (graph, text, label) dicts for the fusion models above."""
# 
#     def __init__(self, paired_list):
#         self.data = paired_list
# 
#     def __len__(self):
#         return len(self.data)
# 
#     def __getitem__(self, idx):
#         return self.data[idx]
# 
# 
# def fusion_collate(batch):
#     graphs_batch = PyGBatch.from_data_list([item["graph"] for item in batch])
#     input_ids = torch.stack([item["input_ids"] for item in batch])
#     attention_mask = torch.stack([item["attention_mask"] for item in batch])
#     labels = torch.tensor([item["label"] for item in batch], dtype=torch.long)
#     return graphs_batch, input_ids, attention_mask, labels

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/contrastive.py
# """Task 4: dual-encoder contrastive model + InfoNCE loss + retrieval metrics (Algorithm 4)."""
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# from torch_geometric.data import Batch as PyGBatch
# from torch_geometric.nn import GraphSAGE, global_mean_pool
# from transformers import AutoModel
# 
# TEMPERATURE = 0.07
# 
# 
# class DualEncoder(nn.Module):
#     """Projects graph and text embeddings into a shared, L2-normalized space."""
# 
#     def __init__(self, bert_name, gnn_in=12, gnn_hidden=64, gnn_layers=3, proj_dim=128, dropout=0.2):
#         super().__init__()
#         self.bert = AutoModel.from_pretrained(bert_name)
#         bert_dim = self.bert.config.hidden_size
#         self.sage = GraphSAGE(in_channels=gnn_in, hidden_channels=gnn_hidden, num_layers=gnn_layers, dropout=dropout)
#         self.text_proj = nn.Linear(bert_dim, proj_dim)
#         self.graph_proj = nn.Linear(gnn_hidden, proj_dim)
# 
#     def encode_text(self, input_ids, attention_mask):
#         out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
#         t = out.last_hidden_state[:, 0, :]
#         return F.normalize(self.text_proj(t), dim=-1)
# 
#     def encode_graph(self, graph_batch):
#         node_h = self.sage(graph_batch.x, graph_batch.edge_index)
#         g = global_mean_pool(node_h, graph_batch.batch)
#         return F.normalize(self.graph_proj(g), dim=-1)
# 
# 
# def contrastive_collate(batch):
#     graphs_batch = PyGBatch.from_data_list([item["graph"] for item in batch])
#     input_ids = torch.stack([item["input_ids"] for item in batch])
#     attention_mask = torch.stack([item["attention_mask"] for item in batch])
#     return graphs_batch, input_ids, attention_mask
# 
# 
# def info_nce_loss(g_embed, t_embed, temperature=TEMPERATURE):
#     logits = g_embed @ t_embed.T / temperature
#     labels = torch.arange(logits.size(0), device=logits.device)
#     loss_g2t = F.cross_entropy(logits, labels)
#     loss_t2g = F.cross_entropy(logits.T, labels)
#     return (loss_g2t + loss_t2g) / 2
# 
# 
# def compute_retrieval_metrics(loader, model, device, k_values=(1, 5, 10)):
#     """Audio<->caption R@K, per the spec's Task 4 evaluation."""
#     model.eval()
#     all_g_embeds, all_t_embeds = [], []
#     with torch.no_grad():
#         for g_batch, ids_batch, mask_batch in loader:
#             g_batch, ids_batch, mask_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device)
#             all_g_embeds.append(model.encode_graph(g_batch).cpu())
#             all_t_embeds.append(model.encode_text(ids_batch, mask_batch).cpu())
# 
#     all_g_embeds = torch.cat(all_g_embeds, dim=0)
#     all_t_embeds = torch.cat(all_t_embeds, dim=0)
#     sim_matrix = all_g_embeds @ all_t_embeds.T
#     N = sim_matrix.size(0)
# 
#     def recall_at_k(sim, k):
#         topk = sim.topk(k, dim=1).indices
#         correct = (topk == torch.arange(N).unsqueeze(1)).any(dim=1)
#         return correct.float().mean().item()
# 
#     results = {}
#     for k in k_values:
#         results[f"audio2caption_R@{k}"] = recall_at_k(sim_matrix, k)
#         results[f"caption2audio_R@{k}"] = recall_at_k(sim_matrix.T, k)
#     return results, sim_matrix

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/train.py
# """Reusable training-loop functions shared across Tasks 1-4."""
# from tqdm.auto import tqdm
# from torch.optim import AdamW
# import torch.nn as nn
# from evaluate import evaluate_text_classifier, evaluate_graph_classifier, evaluate_fusion_classifier
# 
# 
# def train_text_classifier(model, train_loader, val_loader, device, epochs=4, lr=2e-5):
#     """Task 1: BERT tag/genre classifier training loop."""
#     optimizer = AdamW(model.parameters(), lr=lr)
#     criterion = nn.CrossEntropyLoss()
#     history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}
# 
#     for epoch in range(epochs):
#         model.train()
#         total_loss = 0
#         for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
#             input_ids = batch["input_ids"].to(device)
#             attention_mask = batch["attention_mask"].to(device)
#             labels = batch["label"].to(device)
# 
#             optimizer.zero_grad()
#             logits = model(input_ids, attention_mask)
#             loss = criterion(logits, labels)
#             loss.backward()
#             optimizer.step()
#             total_loss += loss.item()
# 
#         val_macro_f1, val_micro_f1, _, _ = evaluate_text_classifier(model, val_loader, device)
#         history["train_loss"].append(total_loss / len(train_loader))
#         history["val_macro_f1"].append(val_macro_f1)
#         history["val_micro_f1"].append(val_micro_f1)
#         print(f"Epoch {epoch+1}: val_macro_f1={val_macro_f1:.4f} val_micro_f1={val_micro_f1:.4f}")
#     return history
# 
# 
# def train_graph_classifier(model, train_loader, val_loader, device, epochs=30, lr=1e-3):
#     """Task 2: GraphSAGE genre classifier training loop."""
#     optimizer = AdamW(model.parameters(), lr=lr)
#     criterion = nn.CrossEntropyLoss()
#     history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}
# 
#     for epoch in range(epochs):
#         model.train()
#         total_loss = 0
#         for batch in train_loader:
#             batch = batch.to(device)
#             optimizer.zero_grad()
#             logits = model(batch.x, batch.edge_index, batch.batch)
#             loss = criterion(logits, batch.y)
#             loss.backward()
#             optimizer.step()
#             total_loss += loss.item()
# 
#         val_macro_f1, val_micro_f1 = evaluate_graph_classifier(model, val_loader, device)
#         history["train_loss"].append(total_loss / len(train_loader))
#         history["val_macro_f1"].append(val_macro_f1)
#         history["val_micro_f1"].append(val_micro_f1)
#         if (epoch + 1) % 5 == 0 or epoch == 0:
#             print(f"Epoch {epoch+1}: val_macro_f1={val_macro_f1:.4f} val_micro_f1={val_micro_f1:.4f}")
#     return history
# 
# 
# def train_fusion_model(model, train_loader, val_loader, device, ckpt_path, epochs=4, lr=2e-5):
#     """Tasks 3: fusion model training loop (works for both FusionModel and EarlyConcatFusion)."""
#     import torch
#     optimizer = AdamW(model.parameters(), lr=lr)
#     criterion = nn.CrossEntropyLoss()
#     history = {"train_loss": [], "val_macro_f1": [], "val_micro_f1": []}
#     best_val_f1 = 0
# 
#     for epoch in range(epochs):
#         model.train()
#         total_loss = 0
#         for g_batch, ids_batch, mask_batch, label_batch in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
#             g_batch, ids_batch, mask_batch, label_batch = (
#                 g_batch.to(device), ids_batch.to(device), mask_batch.to(device), label_batch.to(device)
#             )
#             optimizer.zero_grad()
#             logits = model(g_batch, ids_batch, mask_batch)
#             loss = criterion(logits, label_batch)
#             loss.backward()
#             optimizer.step()
#             total_loss += loss.item()
# 
#         val_macro_f1, val_micro_f1 = evaluate_fusion_classifier(model, val_loader, device)
#         history["train_loss"].append(total_loss / len(train_loader))
#         history["val_macro_f1"].append(val_macro_f1)
#         history["val_micro_f1"].append(val_micro_f1)
# 
#         if val_macro_f1 > best_val_f1:
#             best_val_f1 = val_macro_f1
#             torch.save(model.state_dict(), ckpt_path)
#         print(f"Epoch {epoch+1}: val_macro_f1={val_macro_f1:.4f} val_micro_f1={val_micro_f1:.4f}")
#     return history, best_val_f1
# 
# 
# def train_contrastive(model, train_loader, device, epochs=15, lr=2e-5):
#     """Task 4: dual-encoder contrastive training loop (InfoNCE)."""
#     from contrastive import info_nce_loss
#     optimizer = AdamW(model.parameters(), lr=lr)
#     history = {"train_loss": []}
# 
#     for epoch in range(epochs):
#         model.train()
#         total_loss = 0
#         for g_batch, ids_batch, mask_batch in train_loader:
#             g_batch, ids_batch, mask_batch = g_batch.to(device), ids_batch.to(device), mask_batch.to(device)
#             optimizer.zero_grad()
#             g_embed = model.encode_graph(g_batch)
#             t_embed = model.encode_text(ids_batch, mask_batch)
#             loss = info_nce_loss(g_embed, t_embed)
#             loss.backward()
#             optimizer.step()
#             total_loss += loss.item()
# 
#         avg_loss = total_loss / len(train_loader)
#         history["train_loss"].append(avg_loss)
#         print(f"Epoch {epoch+1}: loss={avg_loss:.4f}")
#     return history

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/gnn-bert-music-context/src/evaluate.py
# """Evaluation functions for each model type, plus a metrics-saving helper."""
# import json
# import torch
# from sklearn.metrics import f1_score, precision_score, recall_score
# 
# 
# def evaluate_text_classifier(model, loader, device):
#     """Task 1: BERT classifier eval. Returns macro_f1, micro_f1, preds, labels."""
#     model.eval()
#     all_preds, all_labels = [], []
#     with torch.no_grad():
#         for batch in loader:
#             input_ids = batch["input_ids"].to(device)
#             attention_mask = batch["attention_mask"].to(device)
#             labels = batch["label"].to(device)
#             logits = model(input_ids, attention_mask)
#             preds = torch.argmax(logits, dim=1)
#             all_preds.extend(preds.cpu().numpy())
#             all_labels.extend(labels.cpu().numpy())
#     macro_f1 = f1_score(all_labels, all_preds, average="macro")
#     micro_f1 = f1_score(all_labels, all_preds, average="micro")
#     return macro_f1, micro_f1, all_preds, all_labels
# 
# 
# def evaluate_graph_classifier(model, loader, device):
#     """Task 2: GraphSAGE / CNN-style classifier eval (graph batches)."""
#     model.eval()
#     all_preds, all_labels = [], []
#     with torch.no_grad():
#         for batch in loader:
#             batch = batch.to(device)
#             logits = model(batch.x, batch.edge_index, batch.batch)
#             preds = torch.argmax(logits, dim=1)
#             all_preds.extend(preds.cpu().numpy())
#             all_labels.extend(batch.y.cpu().numpy())
#     return f1_score(all_labels, all_preds, average="macro"), f1_score(all_labels, all_preds, average="micro")
# 
# 
# def evaluate_cnn_classifier(model, loader, device):
#     """Task 2 baseline (B2): CNN over mel-spectrogram tensors."""
#     model.eval()
#     all_preds, all_labels = [], []
#     with torch.no_grad():
#         for x_batch, y_batch in loader:
#             x_batch, y_batch = x_batch.to(device), y_batch.to(device)
#             logits = model(x_batch)
#             preds = torch.argmax(logits, dim=1)
#             all_preds.extend(preds.cpu().numpy())
#             all_labels.extend(y_batch.cpu().numpy())
#     return f1_score(all_labels, all_preds, average="macro"), f1_score(all_labels, all_preds, average="micro")
# 
# 
# def evaluate_fusion_classifier(model, loader, device):
#     """Task 3: fusion model eval (graph + text batches)."""
#     model.eval()
#     all_preds, all_labels = [], []
#     with torch.no_grad():
#         for g_batch, ids_batch, mask_batch, label_batch in loader:
#             g_batch, ids_batch, mask_batch, label_batch = (
#                 g_batch.to(device), ids_batch.to(device), mask_batch.to(device), label_batch.to(device)
#             )
#             logits = model(g_batch, ids_batch, mask_batch)
#             preds = torch.argmax(logits, dim=1)
#             all_preds.extend(preds.cpu().numpy())
#             all_labels.extend(label_batch.cpu().numpy())
#     return f1_score(all_labels, all_preds, average="macro"), f1_score(all_labels, all_preds, average="micro")
# 
# 
# def compute_precision_recall(labels, preds):
#     precision = precision_score(labels, preds, average="macro")
#     recall = recall_score(labels, preds, average="macro")
#     return precision, recall
# 
# 
# def save_metrics(metrics: dict, path: str):
#     with open(path, "w") as f:
#         json.dump(metrics, f, indent=2)
#     print(f"Saved metrics to {path}")

!ls /content/gnn-bert-music-context/src/

import nbformat as nbf
import os

PROJECT_DIR = "/content/gnn-bert-music-context"
nb = nbf.v4.new_notebook()
cells = []

cells.append(nbf.v4.new_markdown_cell(
"""# GNN-BERT Music Context — Demo Notebook (Task 2)

Loads the trained Task 2 GraphSAGE model plus one saved segment graph,
and runs a single end-to-end inference: predicting genre purely from audio structure (no text)."""))

cells.append(nbf.v4.new_code_cell(
"""import sys
sys.path.append('/content/gnn-bert-music-context/src')

import torch
import pandas as pd
from torch_geometric.data import Batch as PyGBatch

from gnn_model import GraphSAGEClassifier

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)"""))

cells.append(nbf.v4.new_code_cell(
"""# Recover genre label ordering (matches training-time LabelEncoder order)
METADATA_DIR = f"{PROJECT_DIR}/data/raw/fma_metadata"
tracks = pd.read_csv(f"{METADATA_DIR}/tracks.csv", index_col=0, header=[0, 1])
small = tracks[tracks[('set', 'subset')] == 'small']
GENRE_CLASSES = sorted(small[('track', 'genre_top')].dropna().unique())
print(GENRE_CLASSES)"""))

cells.append(nbf.v4.new_code_cell(
"""# Load one example graph from the saved graph set
all_graphs = torch.load(f"{PROJECT_DIR}/data/graphs/all_graphs.pt", weights_only=False)
graph = all_graphs[0]
print(graph)
print("True label index:", graph.y.item(), "->", GENRE_CLASSES[graph.y.item()])"""))

cells.append(nbf.v4.new_code_cell(
"""# Load the trained GraphSAGE model (Task 2 checkpoint)
model = GraphSAGEClassifier(num_classes=len(GENRE_CLASSES)).to(device)
model.load_state_dict(torch.load(f"{PROJECT_DIR}/results/task2_gnn_model.pt", map_location=device))
model.eval()
print("Model loaded.")"""))

cells.append(nbf.v4.new_code_cell(
"""# Run one end-to-end inference: graph structure -> predicted genre
graph_batch = PyGBatch.from_data_list([graph]).to(device)

with torch.no_grad():
    logits = model(graph_batch.x, graph_batch.edge_index, graph_batch.batch)
    pred_idx = torch.argmax(logits, dim=1).item()

print(f"True genre:      {GENRE_CLASSES[graph.y.item()]}")
print(f"Predicted genre: {GENRE_CLASSES[pred_idx]}")"""))

cells.append(nbf.v4.new_markdown_cell(
"""## Note

This demo uses Task 2's GraphSAGE model, which classifies genre from chord/segment
graph structure alone (no text). Raw FMA metadata is used only to recover genre label
ordering — the model itself only needs the graph and its saved weights."""))

nb['cells'] = cells
os.makedirs(f"{PROJECT_DIR}/notebooks", exist_ok=True)
with open(f"{PROJECT_DIR}/notebooks/demo_context.ipynb", "w") as f:
    nbf.write(nb, f)

print("Saved demo_context.ipynb (Task 2 version)")

# Commented out IPython magic to ensure Python compatibility.
# %run /content/gnn-bert-music-context/notebooks/demo_context.ipynb